# Running this will yield 2 'result' directories, one with a wrapper to run
# a qemu test vm to try out the configurtion and the other containing a sanitary
# qcow2 image.

build:
	nix-build
	# NIX_PATH=$NIX_PATH:nixos-config=./configuration.nix nix-build
